force-app/main/default/objects/SSLoggingSettings__c/SSLoggingSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SSLoggingSettings</label>
</CustomObject>

force-app/main/default/objects/SSLoggingSettings__c/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>The default App Name to group logs by. This displays as the blue text in Papertrail.</description>
    <inlineHelpText>The default App Name to group logs by. This displays as the blue text in Papertrail.</inlineHelpText>
    <label>App Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Log_Layout__c.field-meta.xml
<CustomField>
    <fullName>Log_Layout__c</fullName>
    <description>How logs should be displayed. Autoinjected fields are ${message}, ${logger}, ${level}, and ${date}</description>
    <inlineHelpText>How logs should be displayed. Autoinjected fields are ${message}, ${logger}, ${level}, and ${date}</inlineHelpText>
    <label>Log Layout</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Bridge_Url__c.field-meta.xml
<CustomField>
    <fullName>Logging_Bridge_Url__c</fullName>
    <defaultValue>"https://salesforcelogging.azurewebsites.net/api/Log"</defaultValue>
    <description>The URL to the API endpoint for posting log messages</description>
    <inlineHelpText>The URL to the API endpoint for posting log messages</inlineHelpText>
    <label>Logging Bridge URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Server_Port__c.field-meta.xml
<CustomField>
    <fullName>Logging_Server_Port__c</fullName>
    <description>The port for the logging server the bridge should post to. Found in "Add Systems" dialog in Papertrail.</description>
    <inlineHelpText>The port for the logging server the bridge should post to. Found in "Add Systems" dialog in Papertrail.</inlineHelpText>
    <label>Logging Server Port</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Server_URL__c.field-meta.xml
<CustomField>
    <fullName>Logging_Server_URL__c</fullName>
    <defaultValue>"logsX.papertrailapp.com"</defaultValue>
    <description>The Syslog server logs should be posted to by the Logging Bridge. Server must support the TCP protocol and have TLS enabled. Papertrail is a popular choice for this.</description>
    <inlineHelpText>The Syslog server logs should be posted to by the Logging Bridge. Server must support the TCP protocol and have TLS enabled. Papertrail is a popular choice for this.</inlineHelpText>
    <label>Logging Server URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSLoggingTest.cls
@isTest
class SSLoggingTest {

    private static SSLogging logger = SSLogging.GetCurrentClassLogger();
    private static SSLogging appNamedLogger = SSLogging.GetCurrentClassLogger().withAppName('CustomAppName');
    private static SSLogging namedLogger = SSLogging.GetLogger('CustomLogger');

    @testSetup
    static void setup() {
        SSLoggingSettings__c settings = new SSLoggingSettings__c();
        settings.App_Name__c = 'SSLoggingTesting';
        settings.Logging_Bridge_Url__c = 'http://www.bridge.dev/Log';
        settings.Logging_Server_URL__c = 'http://www.someserver.dev';
        settings.Logging_Server_Port__c = 44444;
        settings.Log_Layout__c = '[${level}] ${message}';

        insert settings;
    }

    @isTest
    static void testInfoLog() {
        Test.setMock(HttpCalloutMock.class, new SalesforceLoggingHttpMock());

        System.assert(logger != null);
        logger.info('Info Test');
        System.assert(true);
    }

    @isTest
    static void testDefaultAppname() {
        System.assertEquals('SSLoggingTesting', logger.appName);
    }

    @isTest
    static void testCanSetAppname() {
        System.assertEquals('CustomAppName', appNamedLogger.appName);
    }

    @isTest
    static void testDefaultLoggerName() {
        System.assertEquals('SSLoggingTest', logger.loggerName);
    }

    @isTest
    static void testNamedLogger() {
        System.assertEquals('CustomLogger', namedLogger.loggerName);
    }

    @isTest
    static void testCanGetSettings() {
        SSLoggingSettings__c settings = SSLoggingSettings__c.getInstance();

        System.assert(settings != null);
        System.assertEquals('SSLoggingTesting', settings.App_Name__c);
    }
}