force-app/main/default/objects/SSLoggingSettings__c/SSLoggingSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SSLoggingSettings</label>
</CustomObject>

force-app/main/default/objects/SSLoggingSettings__c/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>The default App Name to group logs by. This displays as the blue text in Papertrail.</description>
    <inlineHelpText>The default App Name to group logs by. This displays as the blue text in Papertrail.</inlineHelpText>
    <label>App Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Log_Layout__c.field-meta.xml
<CustomField>
    <fullName>Log_Layout__c</fullName>
    <description>How logs should be displayed. Autoinjected fields are ${message}, ${logger}, ${level}, and ${date}</description>
    <inlineHelpText>How logs should be displayed. Autoinjected fields are ${message}, ${logger}, ${level}, and ${date}</inlineHelpText>
    <label>Log Layout</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Bridge_Url__c.field-meta.xml
<CustomField>
    <fullName>Logging_Bridge_Url__c</fullName>
    <defaultValue>"https://salesforcelogging.azurewebsites.net/api/Log"</defaultValue>
    <description>The URL to the API endpoint for posting log messages</description>
    <inlineHelpText>The URL to the API endpoint for posting log messages</inlineHelpText>
    <label>Logging Bridge URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Server_Port__c.field-meta.xml
<CustomField>
    <fullName>Logging_Server_Port__c</fullName>
    <description>The port for the logging server the bridge should post to. Found in "Add Systems" dialog in Papertrail.</description>
    <inlineHelpText>The port for the logging server the bridge should post to. Found in "Add Systems" dialog in Papertrail.</inlineHelpText>
    <label>Logging Server Port</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SSLoggingSettings__c/fields/Logging_Server_URL__c.field-meta.xml
<CustomField>
    <fullName>Logging_Server_URL__c</fullName>
    <defaultValue>"logsX.papertrailapp.com"</defaultValue>
    <description>The Syslog server logs should be posted to by the Logging Bridge. Server must support the TCP protocol and have TLS enabled. Papertrail is a popular choice for this.</description>
    <inlineHelpText>The Syslog server logs should be posted to by the Logging Bridge. Server must support the TCP protocol and have TLS enabled. Papertrail is a popular choice for this.</inlineHelpText>
    <label>Logging Server URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSLogging.cls
public class SSLogging {
    private String hostName;
    @TestVisible
    private String appName;
    @TestVisible
    private String loggerName;

    private SSLoggingSettings__c settings;

    public SSLogging(String loggerName) {
        hostName = URL.getSalesforceBaseUrl().toExternalForm();
        settings = SSLoggingSettings__c.getInstance();
        this.appName = settings.App_Name__c;
        this.loggerName = loggerName;
    }

    public SSLogging withAppName(String appName) {
        this.appName = appName;

        return this;
    }

    public void error(String message) {
        System.debug(System.LoggingLevel.ERROR, message);

        postLogToBridge(new LogMessage(hostName, appName, loggerName, settings, message, 'error'));
    }

    public void warn(String message) {
        System.debug(System.LoggingLevel.WARN, message);

        postLogToBridge(new LogMessage(hostName, appName, loggerName, settings, message, 'warn'));
    }

    public void info(String message) {
        System.debug(System.LoggingLevel.INFO, message);

        postLogToBridge(new LogMessage(hostName, appName, loggerName, settings, message, 'info'));
    }


    public void debug(String message) {
        System.debug(System.LoggingLevel.DEBUG, message);

        postLogToBridge(new LogMessage(hostName, appName, loggerName, settings, message, 'debug'));
    }

    public void trace(String message) {
        System.debug(System.LoggingLevel.FINE, message);

        postLogToBridge(new LogMessage(hostName, appName, loggerName, settings, message, 'trace'));
    }

    private void postLogToBridge(LogMessage log) {
        try {
            HttpRequest request = new HttpRequest();
            Http http = new Http();
            request.setMethod('POST');
            request.setEndpoint(log.bridgeUrl);

            String json = System.JSON.serialize(log);

            request.setBody(json);
            request.setHeader('content-type', 'application/json');

            HttpResponse response = http.send(request);
        } catch (Exception e) {
            System.debug(System.LoggingLevel.ERROR, 'SSLogging: Unable to queue log message.\n Reason: ' + e.getMessage());
        }
    }

    public static SSLogging GetCurrentClassLogger() {
        return new SSLogging(StackTrace.getCallingClassName());
    }

    public static SSLogging GetLogger(String loggerName) {
        return new SSLogging(loggerName);
    }

    public class LogMessage {
        public String hostName;
        public String appName;
        public String loggerName;
        public String message;
        public String logLevel;
        public String bridgeUrl;
        public String loggingServerUrl;
        public Integer loggingServerPort;
        public String logLayout;
        public Datetime sourceDate;


        public LogMessage(String hostName, String appName, String loggerName, SSLoggingSettings__c settings, String message, String logLevel) {
            this.hostName = hostName;
            this.appName = appName;
            this.loggerName = loggerName;
            this.message = message;
            this.logLevel = logLevel;
            this.bridgeUrl = settings.Logging_Bridge_Url__c;
            this.loggingServerUrl = settings.Logging_Server_URL__c;
            this.loggingServerPort = settings.Logging_Server_Port__c.intValue();
            this.logLayout = settings.Log_Layout__c;
            sourceDate = Datetime.now();
        }
    }
}